version: '2.1'

volumes:
  redis-data:

services:

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    build: logstash/
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    links:
      - elasticsearch
      - redis

  kibana:
    build: kibana/
    ports:
      - "5601:5601"
    links:
      - elasticsearch

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
